# List all recipies
default:
    just --list --unsorted

# Build system configuration and switch
build-switch:
    sudo nixos-rebuild switch

# Flake information
flake-info:
	nix flake metadata

# Update nixos
update-nixos:
	nix flake update --update-input nixpkgs

# Update all inputs
update-all-inputs:
	nix flake update
