# List all recipies
default:
    just --list --unsorted

# Build system configuration and switch
build-switch:
    sudo nixos-rebuild switch

# Flake information
flake-info:
	nix flake metadata

# List registry information
registry:
	nix registry list

# Update nixpkgs
update-nixpkgs:
	nix flake lock --update-input nixpkgs

# Update all inputs
update-all-inputs:
	nix flake update
