# List all recipes
default:
    just --list --unsorted

# Build flake
build:
    nix build '.#homeConfigurations.arya.activationPackage'

# Activate
activate:
    ./result/activate

# Build flake (with trace)
build-trace:
    nix build '.#homeConfigurations.arya.activationPackage' --show-trace

# Build via home manager
build-hm:
    home-manager switch --flake .#arya

# Flake metadata
flake-info:
    nix flake metadata

# Update flake
update-flake:
	nix flake update

# Update nixpkgs-unstable
update-unstable:
	nix flake lock --update-input nixpkgs-unstable

# Update specific input
update-flake-input input:
	nix flake lock --update-input {{input}}

# Update home-manager
update-hm:
	nix flake lock --update-input home-manager
