# List all recipes
default:
    just --list --unsorted

# Build flake
build:
    nix build '.#homeConfigurations.elric.activationPackage'

# Build flake (with trace)
build-trace:
    nix build '.#homeConfigurations.elric.activationPackage' --show-trace

# Build via home manager
build-hm:
    home-manager switch --flake .#elric
