# List all recipes
default:
    just --list --unsorted

# Build flake
build:
    nix build '.#homeConfigurations.elric.activationPackage'

# Build flake (with trace)
build-trace:
    nix build '.#homeConfigurations.elric.activationPackage' --show-trace

# Build via home manager
build-hm:
    home-manager switch --flake .#elric

# Update nixpkgs-unstable
update-unstable:
	nix flake lock --update-input nixpkgs-unstable

# Update home-manager
update-hm:
	nix flake lock --update-input home-manager

# Update all inputs
update-all-inputs:
	nix flake update
