templates:
  params:
    author-name: Sibi Prabakaran
    author-email: sibi@psibi.in
    category: Web
    copyright: 'Copyright: (c) 2017 Sibi'
    github-username: psibi
system-ghc: true
skip-ghc-check: true
extra-lib-dirs:
- /home/sibi/.nix-profile/lib
extra-include-dirs:
- /home/sibi/.nix-profile/include
nix:
  enable: false
